version: '3.9'
services:
  recognition-service:
    build:
      context: './recognition-service'
      dockerfile: Dockerfile
    volumes:
      - "./recognition-service:/code/"
    ports:
      - '5001:5000'

  db:
    image: mongo:latest
    restart: unless-stopped
    container_name: moduledb
    ports:
      - "27017:27017"
    volumes: 
      - "./db/db:/data/db"
    logging:
      driver: "none"