version: "3.9"
services:
  api-gateway:
    restart: always
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"

  recognition-service:
    restart: unless-stopped
    build:
      context: "./recognition-service"
      dockerfile: Dockerfile
    volumes:
      - "./recognition-service:/code/"
    ports:
      - "5000"

  detection-service:
    restart: unless-stopped
    build:
      context: "./detection-service"
      dockerfile: Dockerfile
    volumes:
      - "./detection-service:/code/"
    ports:
      - "5000"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./db/db:/data/db"
    logging:
      driver: "none"

  profile-service:
    build:
      context: "./profile-service"
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
    volumes:
      - ./profile-service/public:/app/public

  frontend-app:
    build:
      context: "./frontend-app"
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000"
    volumes:
      - ./frontend-app:/frontend-app/app
      - /frontend-app/app/node_modules
      - /frontend-app/app/.next
